Repository mozilla-services/autopush-rs, pull requests merged in 2018-07, with the labels that each got.

#30 chore: tag 1.48.2
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
Labels: in progress

#31 fix: drop users with too many stored messages
  Cargo.lock
  Cargo.toml
  src/client.rs
  src/protocol.rs
  src/server/mod.rs
  src/settings.rs
  tests/test_integration.py
Labels: bug, in progress, p1

#32 fix: typo and image link fix
  README.md
Labels: in progress

#36 feat: update dependencies
  Cargo.lock
  Cargo.toml
  src/client.rs
Labels: enhancement, in progress, p1

#38 feat: log the nack code in metrics
  src/client.rs
Labels: enhancement, in progress, p1

#39 feat: emit metrics for any failed notif conversions
  src/client.rs
  src/db/commands.rs
  src/db/mod.rs
  src/server/mod.rs
Labels: enhancement, in progress, p1

#40 chore: tag 1.49.0
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
Labels: in progress

#43 chore: tag 1.49.1
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
Labels: in progress

#45 chore: tag 1.49.2
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
Labels: in progress

#46 chore: tag 1.49.3
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
Labels: in progress
