Repository mozilla-services/autopush-rs, pull requests merged in 2018-08, with the labels that each got.

#49 chore: tag 1.49.4
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
Labels: in progress

#50 fix: remove the host tag/log field
  src/client.rs
  src/server/mod.rs
Labels: bug, in progress, p1

#51 chore: tag 1.49.5
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
Labels: in progress

#52 chore: include CIRCLE_TAG in the cache key
  .circleci/config.yml
Labels: bug, in progress, p1

#53 chore: tag 1.49.6
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
Labels: in progress

#54 feat: log out disconnect reason with session statistics
  src/client.rs
Labels: in progress

#56 feat: support webpush API pings
  src/client.rs
  src/protocol.rs
  src/server/mod.rs
  tests/test_integration.py
Labels: enhancement, in progress, p1

#57 chore: tag 1.49.7
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
Labels: in progress

#60 fix: don't render topic/timestamp to the ua
  src/protocol.rs
Labels: enhancement, in progress, p2

#61 chore: tag 1.50.0
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
Labels: in progress

#64 Feat/rustfmt update
  src/client.rs
  src/db/mod.rs
  src/http.rs
  src/server/dispatch.rs
  src/util/send_all.rs
Labels: in progress

#65 feat: upgrade sentry to 0.8.0 and log out errors
  Cargo.lock
  Cargo.toml
  src/client.rs
  src/errors.rs
  src/server/mod.rs
  test-requirements.txt
  tests/test_integration.py
Labels: in progress

#67 chore: tag 1.51.0
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
Labels: in progress

#68 feat: fix sentry test and add release data to sentry errors
  requirements.txt
  src/client.rs
  src/lib.rs
  src/server/mod.rs
  tests/test_integration.py
Labels: in progress
