Repository mozilla-services/autopush-rs, pull requests merged in 2018-06, with the labels that each got.

#6 chore: Dockerfile/ci fixes
  .circleci/config.yml
  .travis.yml
  Dockerfile
Labels: bug

#8 Dockerfile: add version.json
  Dockerfile
  version.json
Labels: in progress

#12 fix: match python autopush's crypto_key format
  Dockerfile
  src/server/mod.rs
  tests/test_integration.py
Labels: bug, in progress, p1

#13 chore: tag 1.48.0
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
Labels: in progress

#15 fix: detailed resolver errors
  src/settings.rs
Labels: in progress

#16 chore: disable default app user for now
  Dockerfile
Labels: bug, in progress

#17 fix: resolve intermittent monthly integration test fails
  tests/test_integration.py
Labels: in progress

#18 fix: fix hostname lookup not including a port
  src/settings.rs
Labels: bug, in progress, p1

#20 refactor: broadcast naming
  src/client.rs
  src/server/mod.rs
  src/util/megaphone.rs
Labels: enhancement, in progress, p1

#21 chore: tag 1.48.1
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
Labels: in progress

#22 feat: setup a cadence error handler
  src/server/metrics.rs
Labels: enhancement, in progress, p1

#27 fix: fix unset connected_at values
  src/client.rs
  src/db/commands.rs
  src/db/mod.rs
Labels: bug, in progress, p1

#28 fix: fix notification fetch spinning
  src/client.rs
  src/db/models.rs
  src/lib.rs
  tests/test_integration.py
Labels: in progress
